Feature
santiago-abstracta/digital-bank-test pull request #1
Opened 2021-12-20 13:26 UTC by santiago-abstracta

Hi Rodri! This is my feature branch. Could you take a look at it?

2021-12-20 20:29 UTC, rquintana-abstracta commented on Documentation.md
> +# Documentation
The name for this file can be more descriptive, as it's basically documentation about test cases and some design decisions. Current name is too generic. Prefer something like: `test_cases.md`

2021-12-20 20:33 UTC, rquintana-abstracta commented on README.md
> +- Install dependencies - Run `npm init wdio .` to start configuring [WebdriverIO](https://drive.google.com/file/d/1-xFcoy4U61wCm7FDRGbmcnyAc-y0JBGn/view?usp=sharing).
This is not really necessary, as every dependency needed for a user to run this project was installed when you ran this command for the first time. All it takes for a user to install needed dependencies from current `package.json` is running an `npm install`, considering they are at your project's root as working directory. That's one of the reasons why keeping your `package.json` updated is important.

2021-12-20 20:38 UTC, rquintana-abstracta commented on pages/base.page.js
> +    expect(await currentPage).to.equal(expectedUrl);
**assertions / expects** don't belong conceptually to a page object. Asserting is one of the direct responsibilities of each test. Page Objects, ideally, abstracts out the concept of a page and its elements, as well as interactions with them (you can create abstractions on top of main general operations with pages, such as logging in or filling in an input), but they do not know about what's a valid behaviour within it. They delegate that to tests.

2021-12-20 20:39 UTC, rquintana-abstracta commented on pages/base.page.js
> +      expect(await cookie[0].name).to.equal(name);
Same comment regarding the responsibility of asserting belonging to each test and not to page objects

2021-12-20 20:45 UTC, rquintana-abstracta commented on pages/base.page.js
> +  async checkIfCookieExists(name) {
This seems to be behaviour that exceeds the scope of a given page, since cookies belong conceptually to the **session**.

You have a couple of options here, but, to simplify, consider making it a method of the base page object (that way you're not binding it to a specific page), and also consider limiting its scope to informing if a cookie exists in current session or not (something like: hasCookie(name), returning a boolean)

2021-12-20 20:48 UTC, rquintana-abstracta commented on pages/base.page.js
> +    const cookie = await browser.getCookies([name]);
this `getCookies()` method seems to return an array of cookies. In this case, a better name for this variable would be **cookies** (plural), that way it inmediately reads like this is holding a collection of cookies.

2021-12-20 20:55 UTC, rquintana-abstracta commented on pages/base.page.js
> +      expect(await cookie[0].name).to.equal(name);
This array can potentially have more that one cookie, and I assume you would like to find the cookie with the matching name, no matter how many of them there are, therefore a safer implementation with try to find a given cookie within every element of the collection. Something like:

```javascript
let matchingCookie = cookies.find((cookie) => cookie.name == name )
```

Reference for the `find()` API for arrays in js: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

2021-12-20 21:09 UTC, rquintana-abstracta commented on pages/base.page.js
> +  async checkIfElementExists(element) {
This method is not necessary, as chai's **expect** API already handles validations for element's existance.

It would be used like:

````javascript
expect(pageObject.element).toBeExisting()
````

Achieving the same behaviour more **idiomatically** and at test level (where validations like this typically belong) instead of at page object level

2021-12-20 21:12 UTC, rquintana-abstracta commented on pages/base.page.js
> +    await element.keys(text);
If you use the `setValue()` method in web elements instead of raw `keys()` you can avoid most of the code necessary for clearing their previous value and clicking them, as it's an abstraction on top of all that.

Doing that, you can simplify it to something like:

```javascript
   async sendText(element, text){
       await element.waitForClickable({ timeout: PAGE_TIMEOUT });
       await element.setValue(text);
}
```
https://v5.webdriver.io/docs/api/element/setValue.html

2021-12-20 21:14 UTC, rquintana-abstracta commented on pages/home.page.js
> +  get logout() {
This can be confused with the action of logging out (even though you call it like an attribute instead of like a method), consider a more specific naming, like **logoutOption** or **logoutMenuItem** to mitigate that potential confusion.

2021-12-20 21:29 UTC, rquintana-abstracta commented on pages/login.page.js
> +  get spanBadgeAndMessage() {
Unlike the rest of the elements, this is named too technically. Consider using a name that describes this element from a user point of view, abstracted from implementation details such as html tag used to represent them. Something like: **loginStateMessage** (it's a tough one to name, I give you that :p )

2021-12-20 21:30 UTC, rquintana-abstracta commented on pages/login.page.js
> +  get signIn() {
Same comment than the logout case. This can be confused with the action of signing in. Maybe add a **Button** suffix to it to make it more explicit

2021-12-20 21:31 UTC, rquintana-abstracta commented on pages/login.page.js
> +  get signUp() {
Same comment regarding potentially confusing name

2021-12-20 21:33 UTC, rquintana-abstracta commented on pages/login.page.js
> +  get usernameValue() {
This is better implemented as a regular method, as you are interacting with an element, not representing it. In page object pattern, only elements are represented as properties, every other action or element's properties checked / extracted are better suited as descriptive methods.

2021-12-20 21:36 UTC, rquintana-abstracta commented on pages/login.page.js
> +  get username() {
I'm thinking if usernameTextBox, passwordTextBox, etc would probably work better for this set of web elements, as sometimes you need to extract their value and would be cool to be able to refer to those values as plain **username** or **password**. Consider that.

2021-12-20 21:37 UTC, rquintana-abstracta commented on pages/login.page.js
> +  get passwordValue() {
same comment as with username

2021-12-20 21:39 UTC, rquintana-abstracta commented on pages/login.page.js
> +  async completeFields(username, password) {
This method name is a bit generic. Consider naming it: `completeCredentials()` or something like that.

2021-12-20 21:40 UTC, rquintana-abstracta commented on pages/login.page.js
> +    expect(await this.usernameValue).to.equal(username);
Same comment regarding the responsibility of expect belonging to tests and not page objects

2021-12-21 15:10 UTC, rquintana-abstracta commented on tests/login.test.js
> +    await LoginPage.checkIfExpectedUrl("login?error");
Prefer, whenever possible, to use elements more directly related to the user experience to assert behaviours in e2e tests. In this case, there is a badge displaying when something goes wrong while logging in. Prefer checking something about it, as URLs can be checked using other types of tests (like integration / api tests).

2021-12-21 15:11 UTC, rquintana-abstracta commented on tests/login.test.js
> +    await LoginPage.checkIfExpectedUrl("login?error");
Same comment regarding prefering web elements over lower-level / less user related entities for assertion purposes.

2021-12-21 15:12 UTC, rquintana-abstracta commented on tests/login.test.js
> +    await LoginPage.checkIfExpectedUrl("login?error");
Same comment regarding prefering web elements over lower-level / less user related entities for assertion purposes.

2021-12-21 15:12 UTC, rquintana-abstracta commented on tests/login.test.js
> +    await LoginPage.checkIfExpectedUrl("login?error");
Same comment regarding prefering web elements over lower-level / less user related entities for assertion purposes.

2021-12-21 15:12 UTC, rquintana-abstracta commented on tests/login.test.js
> +    await LoginPage.checkIfExpectedUrl("login?error");
Same comment regarding prefering web elements over lower-level / less user related entities for assertion purposes.

2021-12-21 15:12 UTC, rquintana-abstracta commented on tests/login.test.js
> +    await LoginPage.checkIfExpectedUrl("login?error");
Same comment regarding prefering web elements over lower-level / less user related entities for assertion purposes.

2021-12-21 15:12 UTC, rquintana-abstracta commented on tests/login.test.js
> +    await LoginPage.checkIfExpectedUrl("login?error");
Same comment regarding prefering web elements over lower-level / less user related entities for assertion purposes.

2021-12-21 15:12 UTC, rquintana-abstracta commented on tests/login.test.js
> +    await LoginPage.checkIfExpectedUrl("login?error");
Same comment regarding prefering web elements over lower-level / less user related entities for assertion purposes.

2021-12-21 15:21 UTC, rquintana-abstracta commented on tests/logout.test.js
> +import { expect } from "chai";
You can use chai's expect globally, no need to import it. if you can't, look up documentation to figure out dependencies or config changes needed to support it.

2021-12-21 15:22 UTC, rquintana-abstracta commented on tests/logout.test.js
> +    await HomePage.checkIfExpectedUrl("login?logout");
Same comment. Prefer to use badge's state for asserting this

2021-12-21 15:26 UTC, santiago-abstracta commented on Documentation.md
> +# Documentation
Done!

2021-12-21 15:27 UTC, rquintana-abstracta commented on tests/logout.test.js
> +    let cookieExists = await HomePage.checkIfCookieExists("remember-me");
Cookies are an implementation detail for e2e tests. In general, the more low-level details your e2e tests rely on ,the flakiest they become (they are, by definition, in charge of testing things from the user perspective. Other test types cover for lower-level scenarios), as sessions can be implemented different eventually, but overall user-level behaviour can remain untouched for longer (as it's more costly / risky to retrain users into a different flow, than it is to change session management implementation). Prefer some other cue (behaviour related) to assert that a session has been finished (like pages you get redirected to when trying to access home page).

2021-12-21 15:31 UTC, rquintana-abstracta commented on tests/login.test.js
> +  it("should redirect to sign up form", async () => {
This test names lacks a pointer to **when** should that happen. Eg. "should redirect to sign up form **when** clicking the sign up button"

2021-12-21 15:32 UTC, rquintana-abstracta commented on tests/logout.test.js
> +  it("should log out of application", async () => {
Same comment as above, add a **when** clause to test definition to make it explicitly what needs to happen in order to get that behaviour (in domain-oriented language, high-level if possible)

2021-12-21 15:33 UTC, rquintana-abstracta commented on tests/logout.test.js
> +  it("should log out of application and remove remember-me cookie", async () => {
Same comment regarding lacking a **when** clause

2021-12-21 15:35 UTC, rquintana-abstracta commented on tests/logout.test.js
> +  it("should tell if elements exist", async () => {
This name is too generic. Make sure to specify what you expect to exist (preferable with a higher-level language, like "it's visible" or "can find the menu item" or the like, as **element** is too low level for this layer, which is the higher abstraction level of your project)

2021-12-21 15:36 UTC, santiago-abstracta commented on README.md
> +- Install dependencies - Run `npm init wdio .` to start configuring [WebdriverIO](https://drive.google.com/file/d/1-xFcoy4U61wCm7FDRGbmcnyAc-y0JBGn/view?usp=sharing).
Done!

2021-12-21 18:53 UTC, santiago-abstracta commented on pages/base.page.js
> +    const cookie = await browser.getCookies([name]);
<img width="524" alt="Captura de pantalla 2021-12-21 124127" src="https://user-images.githubusercontent.com/96072727/146957719-06974a1e-3271-4ed5-897d-b141c4f7fd6c.png">

According to the WebdriverIO documentation, this method retrieves a cookie if you provide the cookie name and all cookies if you don't provide a name, so due to the fact that I didn't find a method to get only one cookie, I used this one and treated the return value as only one cookie (that's why the name of the constant is "cookie").

2021-12-21 18:58 UTC, santiago-abstracta commented on pages/base.page.js
> +    const cookie = await browser.getCookies([name]);
I think the return value is an array composed of objects that contain information about the cookie, and it doesn't matter if you provide a name or not, it always returns an array. The difference is that the array may contain just an element or a bunch of them.

2021-12-21 19:05 UTC, santiago-abstracta commented on pages/base.page.js
> +    const cookie = await browser.getCookies([name]);
So, I believe the find() method you suggested can help me solve that problem. :)

2021-12-21 20:15 UTC, santiago-abstracta commented on pages/base.page.js
> +    expect(await currentPage).to.equal(expectedUrl);
Done!

2021-12-21 20:17 UTC, santiago-abstracta commented on pages/base.page.js
> +      expect(await cookie[0].name).to.equal(name);
Done!

2021-12-22 12:05 UTC, santiago-abstracta commented on pages/base.page.js
> +      expect(await cookie[0].name).to.equal(name);
Done!

2021-12-22 12:10 UTC, santiago-abstracta commented on pages/base.page.js
> +    await element.keys(text);
Done!

2021-12-22 12:25 UTC, santiago-abstracta commented on pages/login.page.js
> +  get spanBadgeAndMessage() {
Done!

2021-12-22 12:27 UTC, santiago-abstracta commented on pages/login.page.js
> +  get signIn() {
Done!

2021-12-22 12:33 UTC, santiago-abstracta commented on pages/login.page.js
> +  get usernameValue() {
Done!

2021-12-22 12:34 UTC, santiago-abstracta commented on pages/login.page.js
> +  get username() {
Done!

2021-12-22 12:35 UTC, santiago-abstracta commented on pages/login.page.js
> +  get passwordValue() {
Done!

2021-12-22 12:36 UTC, santiago-abstracta commented on pages/login.page.js
> +  async completeFields(username, password) {
Done!

2021-12-22 12:36 UTC, santiago-abstracta commented on pages/login.page.js
> +    expect(await this.usernameValue).to.equal(username);
Done!

2021-12-22 18:15 UTC, santiago-abstracta commented on tests/login.test.js
> +    await LoginPage.checkIfExpectedUrl("login?error");
Done!

2021-12-22 18:16 UTC, santiago-abstracta commented on tests/login.test.js
> +    await LoginPage.checkIfExpectedUrl("login?error");
Done!

2021-12-22 18:17 UTC, santiago-abstracta commented on tests/login.test.js
> +    await LoginPage.checkIfExpectedUrl("login?error");
Done!

2021-12-22 18:17 UTC, santiago-abstracta commented on tests/login.test.js
> +    await LoginPage.checkIfExpectedUrl("login?error");
Done!

2021-12-22 18:17 UTC, santiago-abstracta commented on tests/login.test.js
> +    await LoginPage.checkIfExpectedUrl("login?error");
Done!

2021-12-22 18:18 UTC, santiago-abstracta commented on tests/login.test.js
> +    await LoginPage.checkIfExpectedUrl("login?error");
Done!

2021-12-22 18:18 UTC, santiago-abstracta commented on tests/login.test.js
> +    await LoginPage.checkIfExpectedUrl("login?error");
Done!

2021-12-22 18:18 UTC, santiago-abstracta commented on tests/login.test.js
> +    await LoginPage.checkIfExpectedUrl("login?error");
Done!

2021-12-22 18:19 UTC, santiago-abstracta commented on tests/logout.test.js
> +import { expect } from "chai";
Done!

2021-12-22 18:26 UTC, santiago-abstracta commented on tests/logout.test.js
> +    await HomePage.checkIfExpectedUrl("login?logout");
Done!

2021-12-22 18:53 UTC, santiago-abstracta commented on tests/logout.test.js
> +    let cookieExists = await HomePage.checkIfCookieExists("remember-me");
Thank you for the detailed explanation!

2021-12-22 18:55 UTC, santiago-abstracta commented on tests/login.test.js
> +  it("should redirect to sign up form", async () => {
Done!

2021-12-22 18:57 UTC, santiago-abstracta commented on tests/logout.test.js
> +  it("should log out of application", async () => {
Done!

2021-12-22 18:59 UTC, santiago-abstracta commented on tests/logout.test.js
> +  it("should log out of application and remove remember-me cookie", async () => {
Done!

2021-12-23 15:27 UTC, santiago-abstracta commented on tests/logout.test.js
> +    let cookieExists = await HomePage.checkIfCookieExists("remember-me");
`await LoginPage.open("home");`
`expect(await LoginPage.checkIfExpectedUrl("login")).to.equal(true);`

Scenarios: 

1) I log in using valid credentials and **not** checking _Remember Me_ checkbox.
2) I log in using valid credentials and checking _Remember Me_ checkbox.

Thing is I get redirected to the same login page in both scenarios. Bearing in mind _scenario 2_, I would keep the username and password even after logging out, so that I can check if both fields are filled to determine if the remember-me cookie ever existed.

To sum up, I'm keeping a similar method (_hasCookie()_) to solve this problem of not finding a way to do it from a user's perspective.

`expect(await LoginPage.hasCookie("remember-me")).to.equal(false);`

2021-12-23 18:27 UTC, rquintana-abstracta commented on pages/base.page.js
> +    const cookie = await browser.getCookies([name]);
Cool, great research though!

2021-12-27 14:47 UTC, rquintana-abstracta commented on tests/logout.test.js
> +    let cookieExists = await HomePage.checkIfCookieExists("remember-me");
Great research & experiment setup!

2021-12-27 15:41 UTC, rquintana-abstracta commented on pages/base.page.js
> +  async checkIfExpectedUrl(path) {
If this method is used as part of an assertion, I think it's not really needed, as you can use built-in webdriver URL matcher directly on the browser to achieve this result.

```javascript
await expect(browser).toHaveUrlContaining(path)
```

2021-12-27 15:44 UTC, rquintana-abstracta commented on pages/base.page.js
> +    if (matchingCookie != undefined) return true;
You can simplify this to just:

```javascript
return matchingCookie != undefined
```
As that condition already evaluates to a boolean.

2021-12-27 15:49 UTC, rquintana-abstracta commented on pages/login.page.js
> +    return $("/html/body/div[1]/div/div/div[2]/div/span");
This seems like a flaky selector (it's strongly bound to that exact html path, if anything changes throughout that element chain, your selector will break). Only leave it like that if every other selector strategy fails.

2021-12-27 15:53 UTC, rquintana-abstracta commented on pages/login.page.js
> +  async completeCredentials(username, password) {
Consider creating an abstraction level on top of `completeCredentials`, `toggleRememberMe` and `logIn`, as I assume those are strongly cohesive (used together most of the time) and part of the same "flow" that is logging into a page.

Consider encapsulating those flows in methods like: `logInWithRememberMe()` and `logInWithoutRememberMe()`, that completes fields, clicks remember me (or not) and clicks login button. This will improve readability at test level and potentially will remove duplication there as well (as many tests will probably involve sequentially calling those 2/3 methods anyway)

2021-12-27 15:59 UTC, rquintana-abstracta commented on pages/signup.page.js
> +  get titleSelect() {
I think it'll be safer to use "dropdown menu" insted of "select" for this method, as it's more decoupled of the specific html tag used to implement this behavioiur. If page change's implementation later on, your API will be protected from that (only having to change the actual selector, but client code will be able to continue to use the same element with the same name)

2021-12-27 16:07 UTC, rquintana-abstracta commented on tests/login.test.js
> +    expect(await LoginPage.getPassword()).to.equal(validAccount.password);
This asserts are not strictly incorrect, but they make the test lose focus (decreasing SRP adherence), as it's testing three (related) things at once (that inputs are working, and the login specific behaviour is working).

Another observation is that you are basically testing wdio behaviour in those 2 asserts (that it actually writes those strings into an input element), and that's out of the scope of e2e tests as well, and tyipically out of scope of general testing as well (although there's debate about it. Eg. Robert C. Martin advices on testing the sub-set of functionality a library we're using provides for us to make sure it keeps working as expected after changing their versions, etc).

But, IMO, this is not necessary at this point (and, if anything, this is something for the scope of a unit test, not a e2e test)

2021-12-27 16:07 UTC, rquintana-abstracta commented on tests/login.test.js
> +    wdioExpect(await HomePage.userAvatar).toBeDisplayed();
Consider using raw `expect()` API instead of wdioExpect.

2021-12-27 16:08 UTC, rquintana-abstracta commented on tests/login.test.js
> +    expect(await LoginPage.rememberMeCheckbox.isSelected()).to.equal(true);
Same comment about testing lib functionality

2021-12-27 17:09 UTC, rquintana-abstracta commented on tests/login.test.js
> +    wdioExpect(await HomePage.userAvatar).toBeDisplayed();
Same comment about prefering raw `expect()`

2021-12-27 17:09 UTC, rquintana-abstracta commented on tests/login.test.js
> +    expect(await LoginPage.getPassword()).to.equal(invalidAccount.password);
Same comment about testing lib functionality

2021-12-27 17:11 UTC, rquintana-abstracta commented on tests/login.test.js
> +    expect(await LoginPage.loginStateMessage.getText()).to.equal("Error");
Similar comment about prefering wdio matchers for asserting element's properties, for shortness of expression, idiomatic and optimization reasons (they take care of accessing the property instead of you having to figure out exact method to call)

eg.

````javascript
expect(await LoginPage.loginStateMessage)
```

2021-12-27 17:27 UTC, rquintana-abstracta commented on tests/login.test.js
> +    expect(await LoginPage.getPassword()).to.equal(invalidAccount.password);
Same comment about testing lib functionality

2021-12-27 17:28 UTC, rquintana-abstracta commented on tests/login.test.js
> +    expect(await LoginPage.loginStateMessage.getText()).to.equal("Error");
Same comment about prefering wdio matcher for asserting this

2021-12-27 17:33 UTC, rquintana-abstracta commented on tests/login.test.js
> +    expect(await LoginPage.getUsername()).to.equal(invalidAccount.username);
In general, as I see it's a pattern you used throughout all tests, remove lines that asserts lib functionality and replace, whenever possible, expect() sentences for it's wdio matcher based counterpart

2021-12-27 17:36 UTC, rquintana-abstracta commented on tests/logout.test.js
> +  it("should log out of application when clicking the logout button", async () => {
As logging in seems to be a prerequisite for all tests in this suite, consider using a `beforeEach` **hook** in this suite where you put all your login logic, that way, that'll execute before each of the tests, and you only need to declare it once for the whole suite.

2021-12-27 17:39 UTC, rquintana-abstracta requested changes
Implement proposed changes

2021-12-28 15:17 UTC, santiago-abstracta commented on pages/base.page.js
> +  async checkIfExpectedUrl(path) {
Checked!

2021-12-28 15:18 UTC, santiago-abstracta commented on pages/base.page.js
> +    if (matchingCookie != undefined) return true;
Done!

2021-12-28 15:24 UTC, santiago-abstracta commented on pages/login.page.js
> +    return $("/html/body/div[1]/div/div/div[2]/div/span");
I tried to use the class attribute before, but it didn't work. Tried again and found out I was using badge-success class instead of badge-error :I 

It's working now!

2021-12-28 15:26 UTC, santiago-abstracta commented on pages/login.page.js
> +  async completeCredentials(username, password) {
I totally agree!

2021-12-28 15:28 UTC, santiago-abstracta commented on pages/signup.page.js
> +  get titleSelect() {
Done!

2021-12-28 15:30 UTC, santiago-abstracta commented on tests/login.test.js
> +    expect(await LoginPage.getPassword()).to.equal(validAccount.password);
Thanks for your explanation!

2021-12-28 15:31 UTC, santiago-abstracta commented on tests/login.test.js
> +    wdioExpect(await HomePage.userAvatar).toBeDisplayed();
Done!

2021-12-28 15:33 UTC, santiago-abstracta commented on tests/login.test.js
> +    expect(await LoginPage.rememberMeCheckbox.isSelected()).to.equal(true);
Checked!

2021-12-28 15:34 UTC, santiago-abstracta commented on tests/login.test.js
> +    wdioExpect(await HomePage.userAvatar).toBeDisplayed();
Checked!

2021-12-28 15:34 UTC, santiago-abstracta commented on tests/login.test.js
> +    expect(await LoginPage.getPassword()).to.equal(invalidAccount.password);
Checked!

2021-12-28 15:38 UTC, santiago-abstracta commented on tests/login.test.js
> +    expect(await LoginPage.loginStateMessage.getText()).to.equal("Error");
Done!

2021-12-28 15:38 UTC, santiago-abstracta commented on tests/login.test.js
> +    expect(await LoginPage.getPassword()).to.equal(invalidAccount.password);
Checked!

2021-12-28 15:40 UTC, santiago-abstracta commented on tests/login.test.js
> +    expect(await LoginPage.loginStateMessage.getText()).to.equal("Error");
Done!

2021-12-28 15:41 UTC, santiago-abstracta commented on tests/login.test.js
> +    expect(await LoginPage.getUsername()).to.equal(invalidAccount.username);
Done!

2021-12-28 17:41 UTC, santiago-abstracta commented on tests/logout.test.js
> +  it("should log out of application when clicking the logout button", async () => {
Done!

2021-12-28 18:52 UTC, rquintana-abstracta commented on pages/login.page.js
> +    await super.clickElement(await this.signInButton);
Maybe use your current `logIn()` method here, as you already implemented this logic there (maybe rename it to `clickSignInButton()` or something like that to be more specific). Besides, it matches the abstraction level of the rest of the actions (if you leave it like that, this is slightly lower-level than the previous two methods)

2021-12-28 18:52 UTC, rquintana-abstracta commented on pages/login.page.js
> +  async logIn() {
Rename it to `clickSignInButton()` or something like that, based on previous comment

2021-12-28 18:53 UTC, rquintana-abstracta commented on pages/login.page.js
> +    await super.clickElement(await this.signInButton);
Same comment here about using already defined method for performing this

2021-12-28 20:28 UTC, santiago-abstracta commented on pages/login.page.js
> +    await super.clickElement(await this.signInButton);
Done!

2021-12-28 20:28 UTC, santiago-abstracta commented on pages/login.page.js
> +  async logIn() {
Done!

2021-12-28 20:28 UTC, santiago-abstracta commented on pages/login.page.js
> +    await super.clickElement(await this.signInButton);
Done!

2021-12-28 21:29 UTC, rquintana-abstracta approved these changes

2021-12-29 12:14 UTC, merged